#!/bin/bash

ACTION="install"
case ${1} in
	install)
		ACTION="install"
		shift
	;;
	update)
		ACTION="update"
		shift
	;;
	remove)
		ACTION="remove"
		shift
	;;
esac

yum ${ACTION} -y $@
yum clean all
